### ISSUE TITLE
publish latest master as version to pypi?

### ISSUE THREAD

**Issue by beatthat** [behave-restful/behave-restful#49]
Thanks again for super useful tool!

I'm using behave-restful in several projects now both at work and at home. Most places I'm using it I also use the WaitForServer bolt task I had sent you in PR.

Since you merged that PR, can you also release to PyPi? The way it is now, I have to pip install behave-restful from (submodule) source in every project that uses the WaitForServer task.

**Comment by CurroRodriguez** [comment]
@beatthat  I've released this for you.
