### ISSUE TITLE
"the response json matches" should check header content type

### ISSUE THREAD

**Issue by upMKuhn** [behave-restful/behave-restful#51]
In case the server returns non JSON content, the tests blow up with a parsing error. Can you add a check in the step "the response json matches" to verify the content-type is json? 

Thanks

**Comment by CurroRodriguez** [comment]
@upMKuhn Thanks for your comment.

There is a couple of reasons why this is a bad idea. First, the obvious one: If the API you are testing does not return JSON, the test should "blow up". The parsing error is going to show you the traceback to help you identify the problem.

Second, the API might not populate the Content-Type header, or the Content-Type header might be populated with something else than `application/json`. Some APIs will use a vendor specific type based on JSON, so checking the Content-Type header might give false positives.
