### ISSUE TITLE
Add support in request_invoker for Django Test client

### ISSUE THREAD

**Issue by Chouvic** [behave-restful/behave-restful#57]
If the context session is replaced by Django Test Client(e.g. from django.test import Client), the json data would not be passed to request.data. Rather, the data will be in request.META['json']. This change caused issues for ViewSet as two functions(create, update) will need to use request.data object as the input for serializer's data. 

One support could be added in request_invoker, if the context session is Django Test Client then, the send_post(as well as send_put, send_patch) function in request_invoker could be written as the following:

```
def send_post(context):
    """
    """
    params = _get_params(context)
    context.response = context.session.post(
        context.request_url,
        params=params,
        data=context.request_json_payload,
        content_type='application/json'
    )
```

**Comment by CurroRodriguez** [comment]
What is the advantage of using the Django Test Client instead of requests?

**Comment by CurroRodriguez** [comment]
@Chouvic I'm assuming you're all set with this since I got no response. I'm closing the issue. If you still need help, you can open a separate issue.
