### ISSUE TITLE
Provide source code PyPI package

### ISSUE THREAD

**Issue by jason-leng** [behave-restful/behave-restful#60]
The project I'm working on has enabled the pip option `--no-binary :all:` for historical reasons. Since source code PyPI package is no longer available from v0.1.5, it prevents me from installing the latest version of v0.3.0.

Could we please restart providing source code PyPI package again? Many thanks.

**Comment by CurroRodriguez** [comment]
I've enabled source distributions, but I know that there was some issue. I cannot guarantee that I will keep them if the issue appears again. You should try to install 0.3.1.

Thanks for using behave-restful.
