### ISSUE TITLE
What's the meaning of step(the response json matches)?

### ISSUE THREAD

**Issue by cookie220** [behave-restful/behave-restful#65]
when I updated the step json in the sample feature -> the_response_json_matches.feature
the result is pass even if the json is totally different from the response json. I don't know why. From the step, it should validate the given json with response json, but it not show me the same result.
![image](https://user-images.githubusercontent.com/49980541/97518892-22f1d500-19d3-11eb-8949-e902f5d72f71.png)

**Comment by CurroRodriguez** [comment]
@cookie220  How are you running the tests? can you show me the command that you are running?

**Comment by cookie220** [comment]
Hi @CurroRodriguez yes, I run the tests. very simple, just click on the test and right click, then click run the test in pycharm.

**Comment by CurroRodriguez** [comment]
@cookie220 That step matches the response against a [JsonSchema](https://json-schema.org/) definition. Since your definition is not defining any requirements, then it assumes is valid.

**Comment by cookie220** [comment]
Thanks @CurroRodriguez , so if I need a match or partial match with the response , how should I do?

**Comment by CurroRodriguez** [comment]
@cookie220 There are several steps implemented that allow you to verify the values of a response using [JsonPath](https://goessner.net/articles/JsonPath/). 

Look in the feature tests the `then` tests that verify the steps that start with `the response json at ...` Using JsonPath syntax you can verify the specific values you want in the payload.

Keep in mind that I'm using the `jsonpath` module that even though is a very complete implementation of the JsonPath spec, it doesn't support all the features, so the more complex things do not work, but most of the features are well supported.

Let me know if you have any more questions,
