### ISSUE TITLE
add suppot to set custom content-type  

### ISSUE THREAD

**Issue by jokiefer** [behave-restful/behave-restful#67]
# Problem

I use the [django json:api](https://github.com/django-json-api/django-rest-framework-json-api) extension which uses the content-type `application/vnd.api+json` for example. The [JSON:API spec](https://jsonapi.org/format/#content-negotiation-servers) does not allow any other content-types.

 If i want to use the
```gherkin
When the request sends POST
```
step, it **always** uses the content-type `application/json`. This is cause of the current implementation of the `request_invoker` which passes the payload with the `json` param:

```python
def send_post(context):
    """
    """
    headers = _get_request_headers(context)
    params = _get_params(context)
    context.response = context.session.post(
        context.request_url,
        headers=headers,
        params=params,
        json=context.request_json_payload
    )

```
The `requests` library sets the `content-type` by it self, if the payload is passed in with the `json` param. Headers which are prepared before the json setup, will be overwritten. So there is no chance to configure a different content-type.

# Enhancement

Let the user set the `content-type` header if he want.

**Comment by jokiefer** [comment]
It could be done by refactoring the `send_foo()` functions. 

Example:
```python
def _prepare_request(context, method: str, headers, params, json):
    p = PreparedRequest()
    prepare_kwargs = {
        'method': method,
        'url': context.request_url,
        'headers': headers,
        'params': params,
    }
    if 'Content-Type' in headers and headers['Content-Type'] != 'application/json':
        prepare_kwargs.update({
            'data': str(json)
        })
    else:
        prepare_kwargs.update({
            'json': json
        })
    return p.prepare(**prepare_kwargs)


def send_post(context):
    """
    """
    headers = _get_request_headers(context)
    params = _get_params(context)
    prepared_request = _prepare_request(
        context=context, method='POST', headers=headers, params=params, json=context.request_json_payload)
    context.response = context.session.send(prepared_request)
```

**Comment by CurroRodriguez** [comment]
@jokiefer What you need can be done by creating a session object from the requests library and overwritting the `context.session` property in an initialization hook:

```python
# In features/hooks/session_initialization.py
import requests

def before_all(context):
    json_api_session = requests.Session()
    json_api_session.headers.update({'Content-Type": "application/vnd.api+json"}
    context.session = json_api_session
```

Alternatively, you can create a Facade that uses the Django client and provides the requests interface.
