### ISSUE TITLE
Function context.vars.resolve() enters infinite loop with specific input string

### ISSUE THREAD

**Issue by tomyknocker** [behave-restful/behave-restful#68]
When input string for context.vars.resolve() starts with variable name but without '$', function executes indefinitely.
example: 
```python
    context.vars.add('VAR_NAME','value')
    x = context.vars.resolve('{VAR_NAME}')
```

**Comment by CurroRodriguez** [comment]
This should be fixed by PR #69, and it will be included in the next release.
