### ISSUE TITLE
Header and data correlation are not clear 

### ISSUE THREAD

**Issue by MahmoudIMahmoud** [behave-restful/behave-restful#73]
The scenario is I want to login and extract auth token and use it in the next call.
So how to do so?

**Comment by CurroRodriguez** [comment]
@MahmoudIMahmoud  For that, you want to implement the authentication part in a hook and create a session object (requests session) that contains the auth token. Then you replace the `context.session` object with yours. Here's some pseudo-code:

```python
# in session_initialization_hook.py

import requests

def before_all(context):
    token = get_token_somehow()
    headers = {
        'Authorization': token
    }
    session = requests.Session()
    session.headers.update(headers)
    context.session = session
```

If you need to keep multiple sessions, like one authorized and another one un-authorized, you can store them in the context object and create steps to swap between them.
