### ISSUE TITLE
Moving test data from feature files

### ISSUE THREAD

**Issue by matez0** [behave-restful/behave-restful#74]
What do you think about putting the request and response details into python or YAML files instead of in-lining into the feature files?

For example like [here](https://github.com/matez0/behave-rest-test).

I used a similar framework to test REST API workflows including several subsequent API calls. Many scenarios were based on the same set of API endpoints with different data and heavy repetition of the same payload structures. It was hard to read and maintain.

Thanks.

**Comment by CurroRodriguez** [comment]
@matez0 Can you provide an example on how the feature file will look like? I like the fact that everything is right there and not hidden in external files, but if I see an example of what you're saying, I might change my mind.

**Comment by matez0** [comment]
An example for feature file:
```gherkin
Feature: Add a new book to the library collection
    Background:
        Given the library service started
        When LOGIN TO ADMIN PANEL is requested
        Then library service responds OK with API KEY
        
    Scenario: Add a new book
        When ADD A NEW BOOK is requested
        Then library service responds CREATED

    Scenario: Add the same book twice
        When ADD A NEW BOOK is requested
        Then library service responds CREATED
        When ADD A NEW BOOK is requested
        Then library service responds CONFLICT

```
Here the expressions with capital letters (only for visibility) are the references to the proper request details
that can be found in a python or YAML file (e.g. openapi.yaml).
The step implementation shall retrieve these details from the belonging data file (separation of test data and test logic).

I also have a micro template for that kind of test layout with self testing feature files, e.g.:
[request_response.feature](https://github.com/matez0/behave-rest-test/blob/master/behave_restest/request_response.feature)

**Comment by CurroRodriguez** [comment]
@matez0 There's no reason why you can't implement those steps yourself in your project. Those don't look generic enough to be part of the framework.

**Comment by matez0** [comment]
It depends on what is the purpose of the framework.
If it is only for testing a single endpoint once in a scenario, then in-lining the test data into the feature files is acceptable, but maybe a bit overkill to call it BDD.
If it is for testing workflows with the API, then moving the test data into an openapi or python file increases readability and reduces repetition and maintenance cost.

**Comment by CurroRodriguez** [comment]
@matez0 
The framework provides a domain language to test JSON based REST APIs. The verbosity is an advantage in my opinion. Your opinion might differ, and that's fine. The problem with your example is that is specific to your problem domain and not generic enough to be reusable.
